# Generated by Django 5.2.8 on 2025-11-22 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='product.product')),
                ('sublocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='warehouse.sublocation')),
            ],
            options={
                'verbose_name': 'Stock Record',
                'verbose_name_plural': 'Stock Records',
                'unique_together': {('product', 'sublocation')},
            },
        ),
    ]
