# Generated by Django 5.2.8 on 2025-11-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('RAW', 'Raw Material'), ('FIN', 'Finished Goods'), ('PART', 'Part / Component')], max_length=10)),
                ('type', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
    ]
